### ISSUE TITLE
Trouble with some pages

### ISSUE THREAD

**Issue by MNCamargo** [Nazmul7989/laravel-facebook-post#1]
Problem: 

I can select all the pages around 10... but when I look at the list there are a couple of pages 2 or 3 that do not appear to generate the token... do you know why?

I will send a PR to add the video upload function!

**Comment by Nazmul7989** [comment]
It may happen due to role and permission issue of page. But actually i have no idea what is happening there. I have three pages. When i select all pages, all are there without any hassles. 

Your are always welcome to add new feature of this package.
