### ISSUE TITLE
{"error":{"message":"Unsupported get request. Object with ID '61561730669920' does not exist, cannot be loaded due to missing permissions, or does not support t

### ISSUE THREAD

**Issue by xoco70** [Nazmul7989/laravel-facebook-post#2]
Hi, 

I'm trying to use your plugin, but I'm not having the same result as you.

I could get a Long lived Acces token, but only user token type. When asking for page access token, I get : 

```
Invalid Scopes: manage_pages, pages_show_list. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions
```
Also, I can only ask for 2 permissions: 

- email
- user_payment_tokens

I could not find :

```
pages_show_list
pages_read_engagement
pages_manage_engagement
pages_manage_posts
pages_read_user_content
```
Also, in .env, I set `FACEBOOK_PAGE_ID=61561730669920` from my facebook page URL: https://www.facebook.com/profile.php?id=61561730669920 - Is this correct ? I'm not so familiar with FB API ! 

When I try to get all posts with 

`$response = FacebookPost::getPost();`

I get : 

```
{"error":{"message":"Unsupported get request. Object with ID '61561730669920' does not exist, cannot be loaded due to missing permissions, or does not support t #2
```

Is there anything I'm missing ?

**Comment by alexispe** [comment]
Hello, 
Same here but I have the correct permissions, how did you solve the problem? 
Ty

**Comment by xoco70** [comment]
Uyyy ! My bad, I don't remember quite well the fix. 
I think the problem was not in the plugin, but in facebook. I think I was using a user token and not a page app token.
Still, I don't remember so much, I should have written it when I closed the issue. Sorry for that !
